### ISSUE TITLE
sh脚本

### ISSUE THREAD

**Issue by Gingmzmzx** [a-wing/mc-bot#7]
sh脚本运行的时候会突然不定时停止了，服务器消息就无法同步到qq群，直到有人去再启动那个脚本。
是不是wget的问题。
求大佬解决。

**Comment by a-wing** [comment]
报错信息是什么？

**Comment by Gingmzmzx** [comment]
没有报错信息，就莫名其妙停了
![屏幕截图(47)](https://user-images.githubusercontent.com/49107602/159670530-2b16571b-e7f9-4ff7-971f-59480aa09b12.png)

**Comment by Gingmzmzx** [comment]
![屏幕截图(48)](https://user-images.githubusercontent.com/49107602/159671040-02149222-9d82-4c63-868b-898f20839935.png)
我对脚本做出了一些改动，如图

**Comment by a-wing** [comment]
有几个怀疑的地方

1. 那个日志路径是带 hash 的，应该还有其他程序会动到这个路径吧。可能在运行中的某个时刻这个路径里没有文件
2. log rotation 导致的停止。mc 会定期 rotation log。这个在脚本最后输出一下时间，然后对比一个 log 就可以知道了是否是这个原因了
